from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Uuid,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class Source(Base):
    __tablename__ = "sources"

    # Primary key — the source's display name (e.g. "reuters", "bbc").
    # Text PK instead of serial ID because sources are referenced by name
    # throughout the pipeline (scraper config, NDJSON records, frontend).
    source_name: Mapped[str] = mapped_column(String, primary_key=True)

    # "rss" or "html" — determines which scraping strategy the scraper container uses.
    source_type: Mapped[str] = mapped_column(String, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class Article(Base):
    __tablename__ = "articles"

    # sha256(url)[:24] generated by the scraper. Deterministic so re-scraping
    # the same URL produces the same ID, enabling upserts without duplicates.
    article_id: Mapped[str] = mapped_column(String, primary_key=True)

    # Which source this came from. FK to sources table so we can query
    # "all articles from reuters" or "how many sources covered this event".
    source_name: Mapped[str] = mapped_column(
        String, ForeignKey("sources.source_name"), nullable=False
    )

    # Original URL. Unique constraint prevents the same article being stored
    # twice even if the scraper runs multiple times.
    url: Mapped[str] = mapped_column(Text, unique=True, nullable=False)

    title: Mapped[str] = mapped_column(Text, nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    language: Mapped[str] = mapped_column(String, nullable=False)

    # When the article was originally published (from RSS feed or HTML meta).
    # Nullable because not all sources provide this reliably.
    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # When our scraper fetched it.
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    # --- Bias classification results (filled by bias-classifier container) ---
    # Nullable because these are populated after the article is first inserted.
    bias_label: Mapped[str | None] = mapped_column(String, nullable=True)
    bias_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Full per-class probability distribution {"left": 0.1, "center": 0.8, "right": 0.1}.
    # JSONB so we can query/filter on individual scores if needed.
    bias_scores: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # --- Embedding (filled by embedder container) ---
    # Vector dimension must match the embedding model (768 for bge-base-en-v1.5).
    # When swapping to a different model, create a migration to alter the dimension
    # and re-embed all existing articles.
    embedding = mapped_column(Vector(768), nullable=True)

    # --- Cluster assignment (filled by clustering container) ---
    # NULL if HDBSCAN labeled this article as noise (no event assigned).
    # Deferred FK — articles may be inserted before their event row exists
    # within the same load transaction.
    event_id: Mapped[str | None] = mapped_column(
        Uuid, ForeignKey("events.event_id", deferrable=True, initially="DEFERRED"),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        # Find all articles belonging to a specific event.
        # Used by: backend "show articles for this event" query, load stage joins.
        Index("idx_articles_event_id", "event_id"),

        # Filter/sort articles by publication date.
        # Used by: clustering stage (rolling time window), frontend "latest articles" queries.
        Index("idx_articles_published_at", "published_at"),

        # Filter articles by source.
        # Used by: frontend "articles from source X", analytics on source coverage.
        Index("idx_articles_source", "source_name"),

        # Vector similarity search — "find articles similar to this one".
        # ivfflat is an approximate nearest-neighbor index. vector_cosine_ops
        # means it uses cosine similarity (matches our L2-normalized embeddings).
        # lists=100 is a tuning param — higher = more accurate but slower.
        # Requires ANALYZE after bulk inserts to build the index properly.
        Index(
            "idx_articles_embedding",
            "embedding",
            postgresql_using="ivfflat",
            postgresql_with={"lists": 100},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )


class Event(Base):
    __tablename__ = "events"

    # UUID generated per cluster per pipeline run by the clustering container.
    event_id: Mapped[str] = mapped_column(Uuid, primary_key=True)

    # LLM-generated neutral summary synthesizing all articles in this cluster.
    summary: Mapped[str] = mapped_column(Text, nullable=False)

    # Topic label assigned from a fixed taxonomy (e.g. "politics", "technology").
    topic: Mapped[str] = mapped_column(String, nullable=False)

    # How many articles and distinct sources cover this event.
    # Stored denormalized for fast frontend queries (avoids COUNT joins).
    article_count: Mapped[int] = mapped_column(Integer, nullable=False)
    source_count: Mapped[int] = mapped_column(Integer, nullable=False)

    # Time range of articles in this cluster.
    # Used for "events in the last 24 hours" queries without joining articles.
    window_start: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    window_end: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        # Filter events by topic.
        # Used by: frontend "show all politics events", topic-based feeds.
        Index("idx_events_topic", "topic"),

        # Filter events by time window.
        # Used by: frontend "events from this week", dashboard date range filters.
        # Composite index on (start, end) so range queries hit one index.
        Index("idx_events_window", "window_start", "window_end"),
    )
